from workflows import summarize_project, analyze_project
from web_tools import (
    show_web_files, summarize_web_structure,
    trace_frontend_connections, summarize_python_files,
    project_file_counts, largest_files
)
from command_handlers import (
    explain_file_role_command, file_complexity_command, list_routes_command, route_summary_command,
    route_detail_command, route_full_command, route_templates_command, template_routes_command, template_extends_command,
    template_blocks_command, template_forms_command, template_inputs_command, template_required_command,
    template_hidden_command, template_honeypot_command, route_form_map_command, route_fields_command, route_emails_command,
    route_redirects_command, route_files_command, route_security_command, route_warnings_command, route_report_command,
    project_architecture_command, project_health_command, project_focus_command, or_routes_command, or_report_command,
    or_templates_detail_command, or_form_fields_command, or_required_fields_command, or_route_reports_command,
    template_form_actions_command, form_action_route_command, template_action_map_command, draft_template_command,
    draft_route_command, draft_css_command, draft_js_command, draft_page_bundle_command, draft_ai_page_command,
    draft_ai_html_command, review_draft_command, review_html_structure_command, review_validator_command,
    review_validator_warning_command, validate_draft_command, draft_quiz_from_reference_command, draft_quiz_from_file_command,
    show_files, explain_command, read_command, search_command, debug_search_command, show_working_memory, explain_last_file,
    explain_first_file, explain_second_file, explain_third_file, clear_working_memory, find_usage_command, find_function_command,
    trace_button_command, trace_route_command, trace_endpoint_command, trace_id_command
)


ARGUMENT_COMMANDS = {
    "debug search ": debug_search_command,
    "explain file ": explain_file_role_command,
    "explain ": explain_command,
    "read ": read_command,
    "search ": search_command,
    "file complexity ": file_complexity_command,
    "list routes ": list_routes_command,
    "route summary ": route_summary_command,
    "route detail ": route_detail_command,
    "route full ": route_full_command,
    "route templates ": route_templates_command,
    "template routes ": template_routes_command,
    "template extends ": template_extends_command,
    "template blocks ": template_blocks_command,
    "template forms ": template_forms_command,
    "template inputs ": template_inputs_command,
    "template required ": template_required_command,
    "template hidden ": template_hidden_command,
    "template honeypot ": template_honeypot_command,
    "route form map ": route_form_map_command,
    "route fields ": route_fields_command,
    "route emails ": route_emails_command,
    "route redirects ": route_redirects_command,
    "route files ": route_files_command,
    "route security ": route_security_command,
    "route warnings ": route_warnings_command,
    "route report ": route_report_command,
    "or routes ": or_routes_command,
    "or report ": or_report_command,
    "or route reports ": or_route_reports_command,
    "template form actions ": template_form_actions_command,
    "form action route ": form_action_route_command,
    "template action map ": template_action_map_command,
    "draft template ": draft_template_command,
    "draft route ": draft_route_command,
    "draft css ": draft_css_command,
    "draft js ": draft_js_command,
    "draft page bundle ": draft_page_bundle_command,
    "draft quiz from reference ": draft_quiz_from_reference_command,
    "draft quiz from file ": draft_quiz_from_file_command,
    "draft ai page ": draft_ai_page_command,
    "draft ai html ": draft_ai_html_command,
    "review draft ": review_draft_command,
    "review html structure ": review_html_structure_command,
    "review validator warning ": review_validator_warning_command,
    "review validator ": review_validator_command,
    "validate draft ": validate_draft_command,
    "find usage ": find_usage_command,
    "find function ": find_function_command,
    "trace button ": trace_button_command,
    "trace route ": trace_route_command,
    "trace endpoint ": trace_endpoint_command,
    "trace id ": trace_id_command,
}

COMMANDS = {
    "summarize project": summarize_project,
    "analyze project": analyze_project,
    "files": show_files,
    "working memory": show_working_memory,
    "explain last file": explain_last_file,
    "explain first file": explain_first_file,
    "explain second file": explain_second_file,
    "explain third file": explain_third_file,
    "clear working memory": clear_working_memory,
    "web files": show_web_files,
    "web summary": summarize_web_structure,
    "frontend connections": trace_frontend_connections,
    "python files": summarize_python_files,
    "project file counts": project_file_counts,
    "largest files": largest_files,
    "project architecture": project_architecture_command,
    "project health": project_health_command,
    "project focus": project_focus_command,
    "or templates detail": or_templates_detail_command,
    "or form fields": or_form_fields_command,
    "or required fields": or_required_fields_command,
}