from pathlib import Path


CURRENT_PROJECT_DIR = Path(__file__).resolve().parent

AGENT_PROJECT_DIR = CURRENT_PROJECT_DIR
TARGET_PROJECT_DIR = CURRENT_PROJECT_DIR / "target_project"
ACTIVE_PROJECT_DIR = AGENT_PROJECT_DIR